on:
    push:
        branches:
            [ development ]
name: Test App
jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                distribution: 'zulu'
                java-version: '17'
                cache: 'gradle'
            - uses: kuhnroyal/flutter-fvm-config-action@v2
              id: fvm-config-action
              with:
                path: '.fvmrc'
            - uses: subosito/flutter-action@v2
              with:
                flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
                channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
            - name: Install dependencies
              run: flutter pub get
            - name: Generate g.dart
              run: flutter pub run build_runner build --delete-conflicting-outputs
            - name: Verify formatting
              run: dart format .
            - name: Run test
              run: flutter test
            


